# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'
        # https://github.com/actions/go-versions/blob/main/versions-manifest.json

    - name: Build
      run: go build -o goSecE2E -v ./cmd

    # Testing needs to be for every dir because the tests in test-data also have the test suffix resulting in failure when run!
    - name: Test Collect Test Dirs
      run: go test -v ./pkg/seqe2e/collect_test_dirs
